### ISSUE TITLE
Want to use this sdk with android application

### ISSUE THREAD

**Issue by wohhie** [iotsens/iotsens-api-sdk#1]
I am trying to use this SDK with android application. most SDK require gradle operation and sync with the project. But for this SDK I didn't find any gradle compile code. How I can import/attach to my project. 

I already have the sample credentials like APPLICATION_ID, APPLICATION_SECRET and Username and Password. 
https://gist.github.com/wohhie/1a031e66ea16700659d7f5d60e482b82 Please check the error link

**Comment by JavierMF** [comment]
Dear @wohhie ,

The SDK library is not available on any public maven/graddle repository, but you can install it on you local repository executing "mvn install" in the root folder of the project.

Regarding the problem when using the code on Android, from the stacktrace it seems it is not an SDK issue, but an Android programming issue. The application throws an android.os.NetworkOnMainThreadException because network operations, like accessing the IoTsens API, must be performed on background threads.

**Comment by wohhie** [comment]
Thank you @JavierMF for your quick response.
One of my friends suggest me that, make the SDK to Jar and import it in android project. I create the jar and it's perfectly imported to the android project but it shows error in the compile time. So I think its not the way to import this SDK.

if I import the project executing with maven, it will work, right?
